### PR TITLE
Allow loaded FMU to support both CS and ME when available

### PR DESCRIPTION
**Pull request by sharanry**
Currently, when an FMU supports both CS and ME, it defaults to CS without giving the user an option to choose ME. It also links only the CS c-api. This PR changes that and gives the user more options.

CC: @ThummeTo @ChrisRackauckas

### CODE REVIEW

**Comment by ThummeTo** [comment]
Dear @sharanry,

there are three options for simulation: 

`fmiSimulate` ("I dont't care, let the lib decide" -> picks CS if available, else ME)
`fmiSimulateCS` (force CS-simulation, error if CS not supported)
`fmiSimulateME` (force ME-simulation, error if ME not supported)

Does this resolve your issue?

Regards!

**Comment by sharanry** [comment]
@ThummeTo Problem is currently `fmiLoad` doesn't link ME functions when both are available.

**Comment by ThummeTo** [comment]
After reading your commits (and as you wrote), the CS C-API is not connected if both modes are supported, you are right! I will merge as soon as test are finished, thank you!

**Comment by ThummeTo** [comment]
Thanks for contributing!

**Comment by ThummeTo** [comment]
@sharanry -> 0.3.3 ready!

**Pull request merged**
