### PR TITLE
Use less restrictive compat entries, remove manifest and update .gitgnore

### PR DESCRIPTION
**Pull request by sharanry**
- It is recommended not to include Manifest in packages https://pkgdocs.julialang.org/v1/glossary/.
- Updated to include standard julia gitignore from https://github.com/github/gitignore/blob/main/Julia.gitignore
- Compat entries are updated to allow for the latest compatible versions of the dependencies.
- Added CompatHelper bot to help with keeping the compats up-to-date.

### CODE REVIEW

**Comment by ThummeTo** [comment]
Thank you very much. Let me know as soon as you are ready to merge :-)

**Comment by sharanry** [comment]
@ThummeTo I think it is ready for your review.

**Comment by sharanry** [comment]
@ThummeTo Could you tag a release?

**Comment by ThummeTo** [comment]
Of course, just waiting for the (test-)actions to finish ;-)
I will trigger a release then!
Thanks!

**Comment by ThummeTo** [comment]
Registration running!

**Comment by ThummeTo** [comment]
@sharanry Done! Thanks for contributing!

**Pull request merged**
