### PR TITLE
Bump DiffEqCallBack compat

### LINKED ISSUE #222: Request for DiffEqCallbacks v3 compat with FMI v0.10.x
Hey @ThummeTo!

This is a request for a patch release on FMI v0.10.x for DiffEqCallbacks v3.x.x.

I already have a branch here for it -- https://github.com/ThummeTo/FMI.jl/compare/v0.10.3...sharanry:sy/bump_diffeqcallback_compat?expand=1

### PR DESCRIPTION
**Pull request by sharanry**
Resolves #222

### CODE REVIEW

**Comment by ThummeTo** [comment]
looks (action error log) like some dependencies need to be relaxed a little ...

**Comment by ThummeTo** [comment]
- Tests Julia v1.6 (Win/Linux) fail because of unresolvable dependencies, so we can (a) relax dependencies or (b) pull Julia dep to 1.9 (I guess you are not using the 1.6 LTS anyway, do you?)
- Test Julia v1.10 (Linux) fails with 1 error, because of a missing Linux FMU in FMIZoo (that is ok IMO)
- Test Julia v.10 (Windows) succeeded

**Comment by sharanry** [comment]
Yes. I am using Julia 1.10. So the 1.6 failure shouldn't matter. Also 1.11 is expected to be the new LTS. So this shouldn't be a problem shortly.

**Comment by ThummeTo** [comment]
Do you want to do additional tests or are we ready to release?

**Comment by ChrisRackauckas** [comment]
Note this should be safe since the break was in manifold projection callbacks which aren't used here.

**Comment by sharanry** [comment]
> Do you want to do additional tests or are we ready to release?

I am good to do a release.

**Pull request merged**
